### ISSUE TITLE
Select for faggrupper fungerer ikke

### ISSUE THREAD

**Issue by jonasnico** [navikt/sokos-up-attestasjon#49]
- Combobox'ene burde fungere på samme måte som oppdragsinfo
- Skal ikke valg av Faggruppe filtrere ut til færre Fagområde valg? 
- Burde ha en tøm knapp. Hvis bruker skriver inn noe selv, knekker hele komponenten

**Comment by lhartvik** [comment]
Foreslår at vi kaster den jeg laget i sommer og lager en ny basert på https://aksel.nav.no/komponenter/core/combobox#comboboxdemo-react-hook-form

**Comment by takwaiwang** [comment]
#56
